name: Apply
on:
  push:
    branches:
      - master
    paths:
      - 'migrations/**'
      - 'metadata/**'
      - 'seeds/**'
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      # 事前準備
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      # npx だと指定のバージョンを使えないので hasura-cli 側で使いたいバージョンに直接アップデートする
      - run: npx hasura-cli update-cli --version v2.0.1

      # デプロイ
      - run: npx hasura-cli metadata apply --skip-update-check
        env:
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}

      - run: npx hasura-cli migrate apply --database-name default --skip-update-check
        env:
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}

      - run: npx hasura-cli metadata reload --skip-update-check
        env:
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}

      - run: npx hasura-cli seed apply --database-name default --skip-update-check
        env:
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
