# hasura cloudにデプロイする
name: deploy-test
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - 'metadata/**'
      - 'seeds/**'
      - 'README.md' # github actions デバッグのために入れているだけ
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      HASURA_GRAPHQL_ENDPOINT: ${{secrets.HASURA_GRAPHQL_ENDPOINT}}
      HASURA_GRAPHQL_ADMIN_SECRET: ${{secrets.HASURA_GRAPHQL_ADMIN_SECRET}}
      HASURA_GRAPHQL_DATABASE_URL: ${{secrets.HASURA_GRAPHQL_DATABASE_URL}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install hasura CLI
        # npx だと指定のバージョンを使えないので hasura-cli 側で使いたいバージョンに直接アップデートする
        run: npx hasura-cli update-cli --version v2.0.1

      - name: Apply migration
        run: npx hasura-cli migrate apply --skip-update-check --database-name default

      - name: Apply metadata
        run: npx hasura-cli metadata apply --skip-update-check
